services:
  mariadb:
    image: mariadb:12.3.2
    container_name: frappe-mariadb
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: root
    #    healthcheck:
    #      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot" ]
    #      interval: 10s
    #      timeout: 5s
    #      retries: 20
    #      start_period: 30s
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - frappe-network

  redis-cache:
    image: redis:8.8.0-alpine
    container_name: frappe-redis-cache
    restart: unless-stopped
    volumes:
      - redis_cache_data:/data
    networks:
      - frappe-network

  redis-queue:
    image: redis:8.8.0-alpine
    container_name: frappe-redis-queue
    restart: unless-stopped
    volumes:
      - redis_queue_data:/data
    networks:
      - frappe-network

  redis-socketio:
    image: redis:8.8.0-alpine
    container_name: frappe-redis-socketio
    restart: unless-stopped
    volumes:
      - redis_socketio_data:/data
    networks:
      - frappe-network

  frappe:
    image: frappe/bench:v5.31.0
    container_name: frappe-bench
    restart: unless-stopped
    tty: true
    stdin_open: true
    depends_on:
      #      mariadb:
      #        condition: service_healthy
      #      redis-cache:
      #        condition: service_started
      #      redis-queue:
      #        condition: service_started
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      REDIS_SOCKETIO: redis-socketio:6379
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - ./:/app
    networks:
      - frappe-network

volumes:
  mariadb_data:
  redis_cache_data:
  redis_queue_data:
  redis_socketio_data:

networks:
  frappe-network:
    driver: bridge
